# Setup
title:               'Mathfinder 2nd Edition'
tagline:             'Every +1 matters'
description:         'A webpage where I collect all of my Pathfinder 2nd edition math for ease of reference'
url:                 https://mf2ed.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nikolai H

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
